# Generated by Django 5.2.12 on 2026-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the food item', max_length=255)),
                ('calories', models.FloatField(help_text='Calories per serving')),
                ('protein', models.FloatField(help_text='Protein in grams per serving')),
                ('carbs', models.FloatField(help_text='Carbohydrates in grams per serving')),
                ('fats', models.FloatField(help_text='Fats in grams per serving')),
                ('serving_size', models.CharField(default='100g', help_text='Description of one serving', max_length=100)),
                ('category', models.CharField(default='General', help_text='Food category (e.g. Protein, Grains)', max_length=100)),
            ],
            options={
                'db_table': 'django_meals',
                'ordering': ['name'],
            },
        ),
    ]
