# Generated by Django 5.2.12 on 2026-04-07 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(help_text='Date in YYYY-MM-DD format', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django_daily_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1.0, help_text='Number of servings consumed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logs.dailylog')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='meals.meal')),
            ],
            options={
                'db_table': 'django_log_entries',
                'ordering': ['id'],
            },
        ),
    ]
